### ISSUE TITLE
[Management] GetOfferByID - Potential injection

### ISSUE THREAD

**Issue by ScottWalkerAU** [SENG3150Connections/Project#15]
**File:** Management.Actions.GetOfferByID.java
**Line:** 34
**Issue:**
SQL Injection is possible with the `.where("id=" + id)` function call, sanitisation is required.

**Suggested solution:**
Replace with `.where(HOTELS.ID.eq(UInteger.valueOf(id)))`

**Comment by Freakout2114** [comment]
Followed the Suggested solution and updated the code accordingly.
