### ISSUE TITLE
[Management] GetOfferByID - IndexOutOfBoundsException

### ISSUE THREAD

**Issue by ScottWalkerAU** [SENG3150Connections/Project#16]
**File:** Management.Actions.GetOfferByID.java
**Line:** 34
**Issue:**
If id is null, or the record does not exist, the `.get(0)` call results in an index out of bounds exception.

**Suggested solution:**
Do a test on the size of the resultSet before calling `.get(0)`

**Comment by Freakout2114** [comment]
Added in a test to check if there was currently one result found from the query. Otherwise the function now returns null.
