### ISSUE TITLE
[Authentication] CallbackAction - Loading callback when not coming from auth0

### ISSUE THREAD

**Issue by ScottWalkerAU** [SENG3150Connections/Project#23]
**File:** Authentication.CallbackAction
**Line:** 66
**Issue:**
`com.auth0.InvalidRequestException: The request contains an error: a0.missing_authorization_code` is thrown when testing the action with no parameters.

**Suggested Solution:**
Wrap the call in a `try` block with `catch(InvalidRequestException e) { return LOGIN; }`

**Comment by sebbeth** [comment]
Fixed issue by adding exception handling
