### ISSUE TITLE
[Cart] CartRestaurant- voucherPrice stored as Double returned as double

### ISSUE THREAD

**Issue by jackratcliffe** [SENG3150Connections/Project#32]
**File**: Cart.CartRestaurant.java
**Line**: 65 to 67
**Issue**:
The voucherPrice is stored as Double and initially set to null. getPrice() returns the type double and if the price is not changed from its initial value throws a NullPointerException when called.

**Comment by ScottWalkerAU** [comment]
Closed by request of Jack
